name : testing code on push
on : [push]
runs-on : windows-latest
steps:
  - name: Checkout Code
    uses: actions/checkout@v4
  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'zulu'
      cache: 'maven'
  - name: Set up Maven
    uses: stCarolas/setup-maven@v5
    with:
      maven-version: 3.9.5
  - uses: browser-actions/setup-edge@v1
    with:
      edge-version: stable
  - name: Print Edge version
    run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion
  - name: Run tests
    continue-on-error: true
    run : mvn clean test